Add HTML and CSS part for Novi recepti
tonkec/recepti_alumni pull request #1
Opened 2024-02-12 19:03 UTC by valentinaotocan

2024-02-17 07:45 UTC, tonkec commented on pages/add-recipe/add-recipe.html
> +    <textarea placeholder="Postupak pripreme" style="height:200px"></textarea>
inline styles

2024-02-17 07:45 UTC, tonkec commented on style.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap');
ista stvar ko i na drugom MR-u

2024-02-17 07:45 UTC, tonkec commented on style.css
> +  background-color: var(--light-gray);
Ovo je malo problematicno. Zasto bi svi elementi imali isti bg color i font-size? Vjerojatno ces poslije to prebrisat s nekim drugim propertyjima

2024-02-17 07:45 UTC, tonkec commented on pages/add-recipe/add-recipe.html
> +  <link rel="stylesheet" href="add-recipe.css">
bilo bi dobro da imamo `title`

2024-02-22 14:52 UTC, tonkec requested changes

2024-02-22 14:52 UTC, tonkec commented on pages/add-recipe/add-recipe.css
> +  height: 12.5rem;
zasto fixni height?

2024-02-23 16:50 UTC, valentinaotocan commented on pages/add-recipe/add-recipe.css
> +  height: 12.5rem;
Ako ne stavimo visinu ovo izgleda ovako:
![image](https://github.com/tonkec/recepti_alumni/assets/81707177/e7bb5332-61d2-4cd4-9ca8-fccc7dfd7c57)
A ako stavimo fixnuiheight on svejedno dopuštata da se height elementa textarea prilagođava (smanjuje ili povećava).

2024-03-13 07:21 UTC, merged